"""empty message

Revision ID: 236c876e5470
Revises: c5ada152dca4
Create Date: 2017-10-28 10:40:46.517717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236c876e5470'
down_revision = 'c5ada152dca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'expense', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'user_id')
    # ### end Alembic commands ###
